#!/bin/sh

echo "-- COMPUTER GRAPHICS PROJECT - GROUP X IS LOADING --"

echo "[1/3] Configure..."

cmake -B ./build -S . && \

echo "[2/3] Make..."

cmake --build ./build/ && \

echo "[3/3] Execute..."

./build/CGProject
